id: P9D428540
initial_creation_type: input
source_metadata:
  title: Kangyur
  language: it
  description: 'Texts from and related to the Kangyur (bka'' ''gyur), the Tibetan
    canonical collection of the Buddha''s Word (bka'') in translation (''gyur):'
  volume:
    f292d9dd63294ceeba08a43aef4bb129:
      title: The Heart of the Transcendent Perfection of Wisdom
      parent: Sūtra
    ff6e60d573844c18bbae7068157e8e31:
      title: The Noble Mahāyāna Sūtra entitled The Wisdom of the Hour of Death
      parent: Sūtra
    09d878101b4f46d4a2ee8252c4a1d6b3:
      title: The Noble Sūtra Teaching the Eleven Perceptions
      parent: Sūtra
    0737deeda313493ebd81331dafdb8181:
      title: The Noble Sūtra of Recalling the Three Jewels
      parent: Sūtra
    59d23161731846d9a7f899b18118be5d:
      title: The Noble Sūtra of the Teaching on the Four Factors
      parent: Sūtra
    c4bb463836904a308dbc2554d8b5b83e:
      title: The Perfection of Wisdom, Mother of All Tathāgatas, ‘In One Syllable’
      parent: Sūtra
    1cec49187ab349c3a64863824bacc51c:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    3b8ddb2350f9441da6cf2e1b0c9aad83:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantra
    7930333600a845668f433964ca608412:
      title: The Auspicious Verses of the Seven Successive Buddhas
      parent: Tantra
    e26c1bb9eec94a4ca113c46bd5d22636:
      title: The Noble Mārīcī Dhāraṇī
      parent: Tantra
    454dee738b8d469582d93db81b5c4379:
      title: The Praise to Tārā with Twenty-One Verses of Homage and The Excellent
        Benefits of Reciting the Praise
      parent: Tantra
    916129ec317d4a109b6e40b9b65f2c80:
      title: The Dhāraṇī of Stream of Wealth (Vasudhārā)
      parent: Dhāraṇī
    f7c7c4a9a3314d55a89daba7e4458083:
      title: 'The King of Aspiration Prayers: Samantabhadra''s “Aspiration to Good
        Actions” (Zangchö Mönlam)'
      parent: Dhāraṇī
    df7fe60048774022acc2ee3affb8c82b:
      title: The Noble Dhāraṇī of The Supreme Accomplishment of Sitātapatrā Born from
        the Tathāgata’s Uṣṇīṣa, the Great Invincible Dispeller
      parent: Dhāraṇī
    f5cb373aa70b4f30b6c9cd55da0e5541:
      title: The Noble Essence of Dependent Origination
      parent: Dhāraṇī
    d3131b4350874b2cbe024761bb8a855f:
      title: The Noble Incantation entitled ‘The Rituals for the Blue-Clad Vajrapāṇi’
      parent: Dhāraṇī
    c7f8297e9aac41d4bfb52ff242b44dc5:
      title: The Dhāraṇīs That Encapsulate the Essence of the Kangyur, the Collected
        Words of the Buddha
      parent: Dhāraṇī
created_at: '2022-03-01T04:03:55.008419'
last_modified_at: '2022-03-01T04:03:55.008421'
